try {
  throw new Error('erro')
} catch (error) {
  
} finally {
  console.log('coelhiho')
}